#!/usr/bin/bash
PATH_TO_NOTES="$HOME"
note(){
if [ $# -eq 1 ]; then
vim ~/.notes/$@
else
if [ -d ~/.notes/$1 ]; then
 :
else
mkdir ~/.notes/$1
fi
vim ~/.notes/$1/$2
fi
}

#note(){
#vim -c hi\ Normal\ ctermbg=White\ ctermfg=Black  ~/.notes/$@
#}
nls(){
ls -c ~/.notes/ | grep "$*"
}

nt(){
echo $@ >> ~/.note
}
nr(){
Echo $#
if [ $# -eq 2 ]; then
mv ~/.notes/$1 ~/.notes/$2
else
echo "The note rename requires just 2 arguments \"original note name\" \"new note name\""
fi

}
nsearch(){
grep -inr "$*" ~/.notes/*
}
nall(){
cat ~/.notes/*
}
ntoday(){
find  ~/.notes/  -mtime -1 -type f -print 
}
nopen(){
zenity --text-info --filename="$PATH_TO_NOTES/.notes/$*" &
}
nremove(){
rm ~/.notes/$*
}
