#xsetroot -cursor_name left_ptr
source ~/repos/dotfiles/X/input/keyboard

# Start the screensaver
# xscreensaver -no-splash &

# URXVT Daemon
urxvtd -q -o -f 

# Remind me to stretch my hands
#xwrits +clock +breakclock +idle +top typetime=55 break=5 after=10 -multiply break=7 &

# Disable the bell.
xset b off 

# Restore wallpaper
nitrogen --restore

# Hide the mouse pointer
unclutter --timeout 5 &

#automatically lock the screen using slock 
#xautolock -time 30 -locker slock &

#xss lock
xss-lock -- slock &

# Set DISPLAY env variable, required for Dunst
systemctl --user import-environment DISPLAY

# Start pulse audio
pulseaudio -D

#x-on-resize
x-on-resize --config ~/.monitor_script.sh --start &
# Start my favorite WM
xmonad 
#exec startxfce4
#exec startplasma-x11
