# Configuration for the z-shell
D=~/repos/dotfiles

# ZSH related files #
Z=~/.zsh
fpath=($Z/completions/ $fpath)
[ -f $Z/functions.zsh ] && source $Z/functions.zsh 
[ -f $Z/zle.zsh ] && source $Z/zle.zsh
[ -f $Z/options.zsh ] && source $Z/options.zsh
[ -f $Z/aliases.zsh ] && source $Z/aliases.zsh
[ -f $Z/environment.zsh ] && source $Z/environment.zsh
[ -f $Z/prompt.zsh ] && source $Z/prompt.zsh
[ -f $Z/completion.zsh ] && source $Z/completion.zsh
[ -f ~/.configs ] && source ~/.configs

# Set up some colors for directory listings.
if (( C == 256 )); then
	source $Z/ls_colors_256.zsh
fi

# Source the alias file 
[ -f $D/bash-scripts/alias ] && source $D/bash-scripts/alias

# Source the note script 
[ -f $D/bash-scripts/note_script ] && source $D/bash-scripts/note_script

# Source script file if it exists
[ -f ~/.script.sh ] && source ~/.script.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#Source zsh flie
source /home/abhinav/repos/app-repos/z/z.sh
